Ryuuzu1218/freemarket_sample_64b

README.md

ReadmeにDB設計を行った
ER図
www.lucidchart.com/documents/edit/e448f659-ecbd-475e-8e04-d5af477d18e4/0_0
DB設計をすることで何が必要となってくるか視覚的に分かりやすくする為

designed DB

---

app/assets/stylesheets/modules/user.scss

コンフリクトで消えたコードを修正した
エラーが出て画面が表示されなかった為

conflict_re

---

app/models/item.rb
db/migrate/20200321104355_create_items.rb
test/fixtures/items.yml
test/models/item_test.rb

#WHAT
itemテーブルのマイグレーションファイルを作成しました。
カラム名、アソシエーションの抜け漏れ、スペルミスが無いかの確認お願いします。
アソシエーションの設定は他テーブルができていないためコメントアウトしてあります。
#WHY
スペルミス、設定ミスを事前に防ぐため。

マイグレーションファイル確認

---

app/assets/javascripts/card.coffee
app/controllers/card_controller.rb
app/helpers/card_helper.rb
app/views/card/new.html.haml
app/views/card/show.html.haml
config/routes.rb
test/controllers/card_controller_test.rb

クレジットカード登録画面、確認画面へのコントローラとルーティングの作成
支払い方法にクレジットカードが選ぶことができれば、振込などの手間がなくユーザーが取引を行うことができるため。

create card controller with view

---

app/assets/stylesheets/_banner.scss
app/assets/stylesheets/_exhibition-btn.scss
app/assets/stylesheets/_top-page.scss
app/assets/stylesheets/items.scss
app/views/items/_banner.html.haml
app/views/items/_exhibition-btn.html.haml
app/views/items/_toppage.html.haml
app/views/items/index.html.haml

トップページのバナー、出品ボタンの部分テンプレート化
_banner.html.haml
_exhibition-btn.html.haml
他のページでも使う必要があるため

separate banner,exhibition-btn

---

config/routes.rb

users route change

---

app/assets/stylesheets/_breadcrumb.scss
app/assets/stylesheets/mypage.scss
app/views/users/_breadcrumb.html.haml
app/views/users/show.html.haml

ヘッダーの下の部分を作った
今どこにあるのか視覚的に分かりやすくする為
今回は土台を作っただけだが、本格的な実装はサーバーサイドのパンくずの時とする

breadcrumb_base

---

app/assets/stylesheets/_leftbar.scss
app/views/users/_leftbar.html.haml
app/views/users/show.html.haml

親要素の追加
親要素を追加することで、他のパーツと上手く組み合わせられるようにする為。

Separate bar

---

db/seeds.rb

#WHAT
categoryテーブルにデータを入れるためにseed.rbを編集しました。
#WHY
categoryテーブルにレコードを作成するため

seed.rbの共有

---

app/assets/stylesheets/_items-list.scss
app/assets/stylesheets/_top-items.scss
app/assets/stylesheets/_top-page.scss
app/assets/stylesheets/items.scss
app/views/items/_item-list.html.haml
app/views/items/_top-item.html.haml
app/views/items/_toppage.html.haml
app/views/items/index.html.haml

商品一覧ページの実装（ビューのみ）
商品一覧ページがあることで、ユーザーの購買意欲が高まると思われる。

Items.index

---

app/assets/stylesheets/_banner.scss

bannerの背景画像が表示されるように修正。
背景画像があることで、セクションがわかりやすくなるため。

add image-url

---

Gemfile
Gemfile.lock
app/assets/javascripts/satou.js
app/models/address.rb
app/models/condition.rb
app/models/delivery_charge.rb
app/models/item.rb
app/models/prefecture.rb
app/models/sending_days.rb
app/views/items/new.html.haml
db/migrate/20200402134705_create_addresses.rb
db/schema.rb
test/fixtures/addresses.yml
test/models/address_test.rb

#WHAT
active_hash導入のために、addressテーブルを作成し、addressテーブルに紐づくprefectureモデル、itemテーブルに紐づくconditionモデル、delivery_chargeモデル、sending_daysモデルも作成しました。
#WHY
テーブル管理のためにactive_hashを用いたデータテーブルを作成するため。

active_hash

---

app/assets/stylesheets/logout.scss
app/views/users/logout.html.haml

親要素の追加によりビューが崩れたので、それを編集した
調整することで、より見やすくする為
https://gyazo.com/8a60c9ad03ef93550e80f460e5d93554

logout_view_edit

---

db/migrate/20200408125452_add_column_to_users.rb

usersカラムの追記

---

app/views/devise/registrations/new2.html.haml

郵便番号入力欄を追記
https://gyazo.com/9ca9849954f4dabd1d44dd24dc6c32f8
郵便を早く且つ正確に届ける為

add_postal-code

---

app/controllers/application_controller.rb
app/models/user.rb
db/migrate/20200321104355_create_items.rb

userモデルにアソシエーション、バリデーションを記載した。
user情報に紐づけて、他のメッセージ機能や取引機能をもたせたいため。
また、バリデーションによって不正なパスワードなどが登録できないようにすることで、セキュリティが堅牢となる。

User validation&association

---

README.md

READMEのカラムの追加、削除、変更
サーバーサイドでmigrationファイルを作成する際、READMEを見直し、変更が必要だと判断した為

readme_change1

---

app/models/address.rb
db/migrate/20200408130125_add_sending_info_to_address.rb
db/schema.rb

address.rbにバリデーションを追加
phoneカラムのオプションを修正
送付先住所が、空欄で入力されてしまうと取引が遅くなってしまうため。

Address validation

---

app/models/user.rb

user.rbに、名前登録時の全角制限を追加。
全角半角が入り混じると、混乱を招くため。

全角入力のバリデーションを追加

---

.gitignore
Gemfile
Gemfile.lock
app/views/layouts/application.html.haml

クレジットカードでの購入機能実装のための、gemの初期設定を行った
クレジットカードを使用可能にすることで、取引がスムーズに進むため。

Payjsの初期設定

---

spec/factories/addresses.rb
spec/models/address_spec.rb

rspec、factory_botでテストコード作成
https://gyazo.com/78342bbac0f37ec353c9506f1baf38ec
事前にエラーになる場所を確認することで、漏れを防ぐことができる

address_test

---

db/migrate/20200418110930_change_column_to_items.rb

likesのカラムを変更した
フォームに入れる欄がないのに入れていた為

item_migrate_change

---

Gemfile
Gemfile.lock
spec/controllers/registrations_controller_spec.rb
spec/rails_helper.rb
spec/support/controller_macros.rb

アクションが呼ばれたあと、期待したビューが表示されるのか確認
事前にエラーを発見することで、バグを発生させないようにする為

コントローラーのテスト

---

app/assets/javascripts/category.js
app/controllers/items_controller.rb
app/uploaders/item_image_uploader.rb
app/views/items/new.html.haml
db/migrate/20200420144620_rename_delivary_charge_column_to_items.rb
db/schema.rb

カテゴリー選択時に、子、孫カテゴリーが消えなかった問題を解決
category_idをデータベースに登録できるようにした
カテゴリー情報を付加できる事で、アイテムを探しやすくするため

Category funciton fix

---

README.md
app/assets/javascripts/transactions.coffee
app/assets/stylesheets/transactions.scss
app/controllers/card_controller.rb
app/controllers/transactions_controller.rb
app/helpers/transactions_helper.rb
app/models/card.rb
app/models/item.rb
app/models/transaction.rb
app/models/user_transaction.rb
db/migrate/20200420055328_create_cards.rb
db/migrate/20200420061624_create_transactions.rb
db/migrate/20200420062013_create_user_transactions.rb
spec/controllers/transactions_controller_spec.rb
spec/factories/cards.rb
spec/factories/transactions.rb
spec/factories/user_transactions.rb
spec/helpers/transactions_helper_spec.rb
spec/models/card_spec.rb
spec/models/transaction_spec.rb
spec/models/user_transaction_spec.rb

購入機能に必要な、cardテーブル、transactionテーブル、user_transactionテーブル用のマイグレーションファイル作成とtransactionコントローラーを作成。
商品を購入できる事で、物同士の交換などをしなくてよいため。

Creditcard serverside#1

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/_item-list.html.haml
app/views/items/_top-item.html.haml
db/schema.rb

カテゴリーごとにアイテムを一覧表示するようにした
ユーザーがアイテムを見つけやすくするため
https://gyazo.com/b917f21b90026194e3510bcfdfcea70c

3つのカテゴリーごとにアイテムを表示するようにした

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb
spec/factories/categories.rb
spec/factories/items.rb
spec/models/address_spec.rb
spec/models/item_spec.rb
spec/models/user_spec.rb

item.rbのテストを作成した。
データベースに異常な情報が登録されると、取引がうまくいかなくなってしまうため。
https://gyazo.com/96a91db3bb6785c14f1a5acce3e3a5f7

Items controller test@category

---

app/assets/javascripts/satou.js
app/assets/stylesheets/_satou.scss
app/views/items/edit.html.haml

#what
出品した商品の情報を編集・修正する機能を実装した。
#WHY
出品した商品の情報を変える必要が出た時に変更するため。

商品編集(画像詳細)

---

app/assets/javascripts/satou.js
app/controllers/items_controller.rb
app/views/items/edit.html.haml
app/views/items/new.html.haml

#what
商品情報を更新した後、画像の差し替え・削除をできるようにした。
#why
商品の画像を差し替え、購入者にわかりやすく見せられるようにするため。

Satou26商品編集及び更新機能実装

---

app/assets/javascripts/card.js
app/assets/javascripts/payjp.js
app/controllers/card_controller.rb
spec/factories/card.rb
spec/models/card_spec.rb

クレジットカード管理用modelのcard.rbの単体テストを行った。
クレジットカードに異常なデータが登録できないようにするため。
https://gyazo.com/ea1b24892fc89bf1ee1a8cd5436b374b

Cardモデルテスト

---

app/assets/stylesheets/_satou.scss
app/assets/stylesheets/transactions.scss
app/controllers/transactions_controller.rb
app/views/transactions/carderror.html.haml
config/routes.rb

トランザクション処理を用いてコントローラのエラーハンドリングの処理を作成した。
不正なカードを使用している場合に取引が成立してはいけないため
https://gyazo.com/d9c2b7a7557b85bd52738b181ab15015

購入時のエラーハンドリング

---

app/assets/stylesheets/_top-items.scss
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/_header.html.haml
app/views/items/search.html.haml
app/views/items/show.html.haml
config/routes.rb
spec/controllers/items_controller_spec.rb

ページ上部の検索欄から商品名でのあいまい検索ができるようにした。
商品が多くなった時に目当ての商品を探しやすくするため。
https://gyazo.com/659b864538fa88c5eac56e9fd10378a1
https://gyazo.com/16fc6a39e9b6f4e16d065906c5ce862e

商品情報検索lv１　あいまい検索
